
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(790, 545)
        self.Kurs = QtWidgets.QTabWidget(Form)
        self.Kurs.setEnabled(True)
        self.Kurs.setGeometry(QtCore.QRect(0, 0, 1291, 741))
        self.Kurs.setObjectName("Kurs")
        self.Add = QtWidgets.QWidget()
        self.Add.setObjectName("Add")
        self.AviaparkAdd = QtWidgets.QTableWidget(self.Add)
        self.AviaparkAdd.setGeometry(QtCore.QRect(20, 80, 256, 91))
        self.AviaparkAdd.setObjectName("AviaparkAdd")
        self.AviaparkAdd.setColumnCount(1)
        self.AviaparkAdd.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.AviaparkAdd.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.AviaparkAdd.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.AviaparkAdd.setHorizontalHeaderItem(0, item)
        self.AddPassenger = QtWidgets.QTableWidget(self.Add)
        self.AddPassenger.setGeometry(QtCore.QRect(30, 240, 256, 191))
        self.AddPassenger.setObjectName("AddPassenger")
        self.AddPassenger.setColumnCount(1)
        self.AddPassenger.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.AddPassenger.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.AddPassenger.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.AddPassenger.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.AddPassenger.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.AddPassenger.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.AddPassenger.setHorizontalHeaderItem(0, item)
        self.FlightAdd = QtWidgets.QTableWidget(self.Add)
        self.FlightAdd.setGeometry(QtCore.QRect(490, 40, 256, 231))
        self.FlightAdd.setObjectName("FlightAdd")
        self.FlightAdd.setColumnCount(1)
        self.FlightAdd.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.FlightAdd.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlightAdd.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlightAdd.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlightAdd.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlightAdd.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlightAdd.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlightAdd.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlightAdd.setHorizontalHeaderItem(0, item)
        self.AddAviapark = QtWidgets.QPushButton(self.Add)
        self.AddAviapark.setGeometry(QtCore.QRect(40, 170, 191, 31))
        self.AddAviapark.setObjectName("AddAviapark")
        self.AddFlight = QtWidgets.QPushButton(self.Add)
        self.AddFlight.setGeometry(QtCore.QRect(530, 280, 181, 31))
        self.AddFlight.setObjectName("AddFlight")
        self.Add_Passenger_Button = QtWidgets.QPushButton(self.Add)
        self.Add_Passenger_Button.setGeometry(QtCore.QRect(50, 440, 211, 31))
        self.Add_Passenger_Button.setObjectName("Add_Passenger_Button")
        self.Add_on_Flight = QtWidgets.QTableWidget(self.Add)
        self.Add_on_Flight.setGeometry(QtCore.QRect(490, 360, 256, 91))
        self.Add_on_Flight.setObjectName("Add_on_Flight")
        self.Add_on_Flight.setColumnCount(1)
        self.Add_on_Flight.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.Add_on_Flight.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Add_on_Flight.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Add_on_Flight.setHorizontalHeaderItem(0, item)
        self.Add_Passenger_on_board_Button = QtWidgets.QPushButton(self.Add)
        self.Add_Passenger_on_board_Button.setGeometry(QtCore.QRect(520, 460, 191, 31))
        self.Add_Passenger_on_board_Button.setObjectName("Add_Passenger_on_board_Button")
        self.Kurs.addTab(self.Add, "")
        self.Show = QtWidgets.QWidget()
        self.Show.setObjectName("Show")
        self.Show_Aviapark = QtWidgets.QTableWidget(self.Show)
        self.Show_Aviapark.setGeometry(QtCore.QRect(60, 40, 291, 141))
        self.Show_Aviapark.setObjectName("Show_Aviapark")
        self.Show_Aviapark.setColumnCount(2)
        self.Show_Aviapark.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Aviapark.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Aviapark.setHorizontalHeaderItem(1, item)
        self.Show_Aviapark.horizontalHeader().setDefaultSectionSize(120)
        self.Show_Aviapark.horizontalHeader().setMinimumSectionSize(100)
        self.Show_Aviapark_Button = QtWidgets.QPushButton(self.Show)
        self.Show_Aviapark_Button.setGeometry(QtCore.QRect(60, 180, 281, 31))
        self.Show_Aviapark_Button.setObjectName("Show_Aviapark_Button")
        self.Show_Passenger = QtWidgets.QTableWidget(self.Show)
        self.Show_Passenger.setGeometry(QtCore.QRect(60, 260, 321, 191))
        self.Show_Passenger.setObjectName("Show_Passenger")
        self.Show_Passenger.setColumnCount(0)
        self.Show_Passenger.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger.setVerticalHeaderItem(5, item)
        self.Show_Passenger_Button = QtWidgets.QPushButton(self.Show)
        self.Show_Passenger_Button.setGeometry(QtCore.QRect(230, 480, 191, 31))
        self.Show_Passenger_Button.setObjectName("Show_Passenger_Button")
        self.get_ID_Passenger = QtWidgets.QLineEdit(self.Show)
        self.get_ID_Passenger.setGeometry(QtCore.QRect(70, 490, 113, 20))
        self.get_ID_Passenger.setObjectName("get_ID_Passenger")
        self.label = QtWidgets.QLabel(self.Show)
        self.label.setGeometry(QtCore.QRect(50, 460, 151, 20))
        self.label.setObjectName("label")
        self.Show_Flight = QtWidgets.QTableWidget(self.Show)
        self.Show_Flight.setGeometry(QtCore.QRect(480, 260, 256, 211))
        self.Show_Flight.setObjectName("Show_Flight")
        self.Show_Flight.setColumnCount(1)
        self.Show_Flight.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Flight.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Flight.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Flight.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Flight.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Flight.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Flight.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Flight.setHorizontalHeaderItem(0, item)
        self.Show_Flight_Button = QtWidgets.QPushButton(self.Show)
        self.Show_Flight_Button.setGeometry(QtCore.QRect(590, 480, 181, 31))
        self.Show_Flight_Button.setObjectName("Show_Flight_Button")
        self.label_2 = QtWidgets.QLabel(self.Show)
        self.label_2.setGeometry(QtCore.QRect(450, 470, 121, 16))
        self.label_2.setObjectName("label_2")
        self.get_ID_Flight = QtWidgets.QLineEdit(self.Show)
        self.get_ID_Flight.setGeometry(QtCore.QRect(450, 490, 113, 20))
        self.get_ID_Flight.setObjectName("get_ID_Flight")
        self.Show_Passenger_Board = QtWidgets.QTableWidget(self.Show)
        self.Show_Passenger_Board.setGeometry(QtCore.QRect(450, 0, 256, 211))
        self.Show_Passenger_Board.setObjectName("Show_Passenger_Board")
        self.Show_Passenger_Board.setColumnCount(0)
        self.Show_Passenger_Board.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger_Board.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger_Board.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger_Board.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger_Board.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger_Board.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Show_Passenger_Board.setVerticalHeaderItem(5, item)
        self.Show_Passenger_Board_Button = QtWidgets.QPushButton(self.Show)
        self.Show_Passenger_Board_Button.setGeometry(QtCore.QRect(500, 220, 171, 31))
        self.Show_Passenger_Board_Button.setObjectName("Show_Passenger_Board_Button")
        self.Show_Passenger_Edit = QtWidgets.QLineEdit(self.Show)
        self.Show_Passenger_Edit.setGeometry(QtCore.QRect(370, 230, 113, 20))
        self.Show_Passenger_Edit.setObjectName("Show_Passenger_Edit")
        self.label_9 = QtWidgets.QLabel(self.Show)
        self.label_9.setGeometry(QtCore.QRect(370, 210, 111, 16))
        self.label_9.setObjectName("label_9")
        self.Kurs.addTab(self.Show, "")
        self.Del = QtWidgets.QWidget()
        self.Del.setObjectName("Del")
        self.Delete_Passenger = QtWidgets.QTableWidget(self.Del)
        self.Delete_Passenger.setGeometry(QtCore.QRect(10, 0, 331, 221))
        self.Delete_Passenger.setObjectName("Delete_Passenger")
        self.Delete_Passenger.setColumnCount(0)
        self.Delete_Passenger.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Passenger.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Passenger.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Passenger.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Passenger.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Passenger.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Passenger.setVerticalHeaderItem(5, item)
        self.Delete_Passenger.horizontalHeader().setDefaultSectionSize(75)
        self.Delete_ID_Passenger = QtWidgets.QLineEdit(self.Del)
        self.Delete_ID_Passenger.setGeometry(QtCore.QRect(100, 300, 113, 20))
        self.Delete_ID_Passenger.setObjectName("Delete_ID_Passenger")
        self.label_3 = QtWidgets.QLabel(self.Del)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 261, 16))
        self.label_3.setObjectName("label_3")
        self.Delete_Passenger_Button = QtWidgets.QPushButton(self.Del)
        self.Delete_Passenger_Button.setGeometry(QtCore.QRect(70, 330, 181, 31))
        self.Delete_Passenger_Button.setObjectName("Delete_Passenger_Button")
        self.Show_Del_Passenger = QtWidgets.QPushButton(self.Del)
        self.Show_Del_Passenger.setGeometry(QtCore.QRect(60, 230, 191, 41))
        self.Show_Del_Passenger.setObjectName("Show_Del_Passenger")
        self.Delete_Flight = QtWidgets.QTableWidget(self.Del)
        self.Delete_Flight.setGeometry(QtCore.QRect(390, 10, 381, 261))
        self.Delete_Flight.setObjectName("Delete_Flight")
        self.Delete_Flight.setColumnCount(0)
        self.Delete_Flight.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Flight.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Flight.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Flight.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Flight.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Flight.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Flight.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Flight.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Delete_Flight.setVerticalHeaderItem(7, item)
        self.Show_Del_Flight = QtWidgets.QPushButton(self.Del)
        self.Show_Del_Flight.setGeometry(QtCore.QRect(490, 270, 161, 31))
        self.Show_Del_Flight.setObjectName("Show_Del_Flight")
        self.label_7 = QtWidgets.QLabel(self.Del)
        self.label_7.setGeometry(QtCore.QRect(480, 320, 241, 20))
        self.label_7.setObjectName("label_7")
        self.Delete_ID_Flight = QtWidgets.QLineEdit(self.Del)
        self.Delete_ID_Flight.setGeometry(QtCore.QRect(530, 350, 113, 20))
        self.Delete_ID_Flight.setObjectName("Delete_ID_Flight")
        self.Delete_Flight_Button = QtWidgets.QPushButton(self.Del)
        self.Delete_Flight_Button.setGeometry(QtCore.QRect(490, 380, 181, 31))
        self.Delete_Flight_Button.setObjectName("Delete_Flight_Button")
        self.Kurs.addTab(self.Del, "")
        self.Change = QtWidgets.QWidget()
        self.Change.setObjectName("Change")
        self.Change_Table = QtWidgets.QTableWidget(self.Change)
        self.Change_Table.setGeometry(QtCore.QRect(130, 20, 421, 261))
        self.Change_Table.setObjectName("Change_Table")
        self.Change_Table.setColumnCount(0)
        self.Change_Table.setRowCount(0)
        self.label_4 = QtWidgets.QLabel(self.Change)
        self.label_4.setGeometry(QtCore.QRect(570, 50, 211, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Change)
        self.label_5.setGeometry(QtCore.QRect(570, 90, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Change)
        self.label_6.setGeometry(QtCore.QRect(570, 110, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.Change)
        self.label_8.setGeometry(QtCore.QRect(570, 126, 81, 16))
        self.label_8.setObjectName("label_8")
        self.Switch_Edit = QtWidgets.QLineEdit(self.Change)
        self.Switch_Edit.setGeometry(QtCore.QRect(570, 150, 113, 20))
        self.Switch_Edit.setObjectName("Switch_Edit")
        self.Switch_Button = QtWidgets.QPushButton(self.Change)
        self.Switch_Button.setGeometry(QtCore.QRect(570, 180, 121, 31))
        self.Switch_Button.setObjectName("Switch_Button")
        self.Kurs.addTab(self.Change, "")

        self.retranslateUi(Form)
        self.Kurs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Add.setToolTip(_translate("Form", "<html><head/><body><p>Add</p></body></html>"))
        item = self.AviaparkAdd.verticalHeaderItem(0)
        item.setText(_translate("Form", "Название компании"))
        item = self.AviaparkAdd.verticalHeaderItem(1)
        item.setText(_translate("Form", "Местонахождение"))
        item = self.AviaparkAdd.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Данные"))
        item = self.AddPassenger.verticalHeaderItem(0)
        item.setText(_translate("Form", "Имя"))
        item = self.AddPassenger.verticalHeaderItem(1)
        item.setText(_translate("Form", "Фамилия"))
        item = self.AddPassenger.verticalHeaderItem(2)
        item.setText(_translate("Form", "Отчество"))
        item = self.AddPassenger.verticalHeaderItem(3)
        item.setText(_translate("Form", "Номер паспорта"))
        item = self.AddPassenger.verticalHeaderItem(4)
        item.setText(_translate("Form", "Цена билета"))
        item = self.AddPassenger.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Данные"))
        item = self.FlightAdd.verticalHeaderItem(0)
        item.setText(_translate("Form", "Номер рейса"))
        item = self.FlightAdd.verticalHeaderItem(1)
        item.setText(_translate("Form", "Откуда вылетает"))
        item = self.FlightAdd.verticalHeaderItem(2)
        item.setText(_translate("Form", "Куда летит"))
        item = self.FlightAdd.verticalHeaderItem(3)
        item.setText(_translate("Form", "Дата вылета"))
        item = self.FlightAdd.verticalHeaderItem(4)
        item.setText(_translate("Form", "Дата приземления"))
        item = self.FlightAdd.verticalHeaderItem(5)
        item.setText(_translate("Form", "Компания самолета"))
        item = self.FlightAdd.verticalHeaderItem(6)
        item.setText(_translate("Form", "ID_Авиапарка"))
        item = self.FlightAdd.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Данные"))
        self.AddAviapark.setText(_translate("Form", "Добавить данные об авиапарке"))
        self.AddFlight.setText(_translate("Form", "Добавить данные о рейсе"))
        self.Add_Passenger_Button.setText(_translate("Form", "Добавление данных о человеке"))
        item = self.Add_on_Flight.verticalHeaderItem(0)
        item.setText(_translate("Form", "ID_Рейса"))
        item = self.Add_on_Flight.verticalHeaderItem(1)
        item.setText(_translate("Form", "ID_Пассажира"))
        item = self.Add_on_Flight.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Данные"))
        self.Add_Passenger_on_board_Button.setText(_translate("Form", "Добавление пассажира на рейс"))
        self.Kurs.setTabText(self.Kurs.indexOf(self.Add), _translate("Form", "Add"))
        item = self.Show_Aviapark.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название"))
        item = self.Show_Aviapark.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Местонахождение"))
        self.Show_Aviapark_Button.setText(_translate("Form", "Данные об аэропортах"))
        item = self.Show_Passenger.verticalHeaderItem(0)
        item.setText(_translate("Form", "Номер рейса"))
        item = self.Show_Passenger.verticalHeaderItem(1)
        item.setText(_translate("Form", "Имя"))
        item = self.Show_Passenger.verticalHeaderItem(2)
        item.setText(_translate("Form", "Фамилия"))
        item = self.Show_Passenger.verticalHeaderItem(3)
        item.setText(_translate("Form", "Отчество"))
        item = self.Show_Passenger.verticalHeaderItem(4)
        item.setText(_translate("Form", "Номер паспорта"))
        item = self.Show_Passenger.verticalHeaderItem(5)
        item.setText(_translate("Form", "Цена билета"))
        self.Show_Passenger_Button.setText(_translate("Form", "Данные о пассажире"))
        self.label.setText(_translate("Form", "Введите фамилию пассажира"))
        item = self.Show_Flight.verticalHeaderItem(0)
        item.setText(_translate("Form", "Откуда вылетает"))
        item = self.Show_Flight.verticalHeaderItem(1)
        item.setText(_translate("Form", "Куда летит"))
        item = self.Show_Flight.verticalHeaderItem(2)
        item.setText(_translate("Form", "Дата вылета"))
        item = self.Show_Flight.verticalHeaderItem(3)
        item.setText(_translate("Form", "Дата приземления"))
        item = self.Show_Flight.verticalHeaderItem(4)
        item.setText(_translate("Form", "Компания самолета"))
        item = self.Show_Flight.verticalHeaderItem(5)
        item.setText(_translate("Form", "ID_Авиапарка"))
        item = self.Show_Flight.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Данные"))
        self.Show_Flight_Button.setText(_translate("Form", "Данные о рейсе"))
        self.label_2.setText(_translate("Form", "Введите номер рейса"))
        item = self.Show_Passenger_Board.verticalHeaderItem(0)
        item.setText(_translate("Form", "Номер рейса"))
        item = self.Show_Passenger_Board.verticalHeaderItem(1)
        item.setText(_translate("Form", "Имя"))
        item = self.Show_Passenger_Board.verticalHeaderItem(2)
        item.setText(_translate("Form", "Фамилия"))
        item = self.Show_Passenger_Board.verticalHeaderItem(3)
        item.setText(_translate("Form", "Отчетсво"))
        item = self.Show_Passenger_Board.verticalHeaderItem(4)
        item.setText(_translate("Form", "Номер паспорта"))
        item = self.Show_Passenger_Board.verticalHeaderItem(5)
        item.setText(_translate("Form", "Цена билета"))
        self.Show_Passenger_Board_Button.setText(_translate("Form", "Данные о пассажирах на рейсе"))
        self.label_9.setText(_translate("Form", "Введите номер рейса"))
        self.Kurs.setTabText(self.Kurs.indexOf(self.Show), _translate("Form", "Show"))
        self.Delete_Passenger.setSortingEnabled(True)
        item = self.Delete_Passenger.verticalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.Delete_Passenger.verticalHeaderItem(1)
        item.setText(_translate("Form", "Имя"))
        item = self.Delete_Passenger.verticalHeaderItem(2)
        item.setText(_translate("Form", "Фамилия"))
        item = self.Delete_Passenger.verticalHeaderItem(3)
        item.setText(_translate("Form", "Отчество"))
        item = self.Delete_Passenger.verticalHeaderItem(4)
        item.setText(_translate("Form", "Номер паспорта"))
        item = self.Delete_Passenger.verticalHeaderItem(5)
        item.setText(_translate("Form", "Цена билета"))
        self.label_3.setText(_translate("Form", "Введите ID пассажира которого хотите удалить"))
        self.Delete_Passenger_Button.setText(_translate("Form", "Удалить пассажира"))
        self.Show_Del_Passenger.setText(_translate("Form", "Вывод пассажиров для удалиения"))
        item = self.Delete_Flight.verticalHeaderItem(0)
        item.setText(_translate("Form", "ID_Рейса"))
        item = self.Delete_Flight.verticalHeaderItem(1)
        item.setText(_translate("Form", "Номер рейса"))
        item = self.Delete_Flight.verticalHeaderItem(2)
        item.setText(_translate("Form", "Откуда вылетает"))
        item = self.Delete_Flight.verticalHeaderItem(3)
        item.setText(_translate("Form", "Куда летит"))
        item = self.Delete_Flight.verticalHeaderItem(4)
        item.setText(_translate("Form", "Дата вылета"))
        item = self.Delete_Flight.verticalHeaderItem(5)
        item.setText(_translate("Form", "Дата приземления"))
        item = self.Delete_Flight.verticalHeaderItem(6)
        item.setText(_translate("Form", "Компания самолета"))
        item = self.Delete_Flight.verticalHeaderItem(7)
        item.setText(_translate("Form", "ID_Авиапарка"))
        self.Show_Del_Flight.setText(_translate("Form", "Вывод рейсов для удаления"))
        self.label_7.setText(_translate("Form", "Введите ID рейса который хотите удалить"))
        self.Delete_Flight_Button.setText(_translate("Form", "Удалить рейс"))
        self.Kurs.setTabText(self.Kurs.indexOf(self.Del), _translate("Form", "Del"))
        self.label_4.setText(_translate("Form", "Выберите номер таблицу для изменения"))
        self.label_5.setText(_translate("Form", "1 - Авиапарк"))
        self.label_6.setText(_translate("Form", "2 - Рейс"))
        self.label_8.setText(_translate("Form", "3 - Пассажир"))
        self.Switch_Button.setText(_translate("Form", "Вывести таблицу"))
        self.Kurs.setTabText(self.Kurs.indexOf(self.Change), _translate("Form", "Change"))
